services:

  db:
    image: postgres:alpine3.16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: example
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-volume: